import { ThemeProvider } from "@/components/providers/theme-provider"; // Use the correct path
import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
// suppressHydrationWarning helps avoid React warnings
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} font-sans`}>
        {/* Wrap the entire content that should react to theme changes */}
        <ThemeProvider>
          {/* e.g., <Header /> */}
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
